### ISSUE TITLE
recursion error of pwd hash is not default one

### ISSUE THREAD

**Issue by klausfmh** [mhcomm/django-pwdtk#8]
recursion error if loggin in as user whose pwd hash is out of date

If a user's password does not use the default django hashing algorithm, then (when a user logs in)
the hash is recalculated with the new hashing algorithm and saved.

Django signals this as a password change, thuough in reality the password did not change (only its hash in the data base)

This triggers a recursion error (at least with python 2.7 / django 1.8)

**Comment by feenes** [comment]
https://github.com/mhcomm/django-pwdtk/pull/10 should fix the issue.
Testing ...
